# Generated by Django 3.0.7 on 2020-07-06 11:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('picture', models.ImageField(null=True, upload_to='category/')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('short_description', models.TextField(max_length=200, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_picture', models.ImageField(null=True, upload_to='posts/headers')),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='author.Author')),
                ('category', models.ManyToManyField(to='blog.Category')),
                ('tags', models.ManyToManyField(to='blog.Tags')),
            ],
        ),
    ]
