# Generated by Django 3.0.7 on 2020-07-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200706_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_content',
            field=models.TextField(null=True),
        ),
    ]
