# Generated by Django 3.0.7 on 2020-07-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200706_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.ImageField(default='authors/default.jpeg', null=True, upload_to='posts/headers'),
        ),
    ]
