# Generated by Django 3.0.7 on 2020-07-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20200707_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(default='authors/default.jpeg', null=True, upload_to='authors/photos'),
        ),
    ]
