# Generated by Django 3.0.7 on 2020-07-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20200711_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('avatar', models.ImageField(default='main/author.jpg', null=True, upload_to='authors/photos')),
            ],
        ),
    ]
