# Generated by Django 3.0.7 on 2020-07-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_mainconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainConfig',
        ),
    ]
