# Generated by Django 3.0.7 on 2020-07-14 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_mainconfigs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainConfigs',
        ),
    ]
